### PR TITLE
Add ability to set base URL

### PR DESCRIPTION
**Pull request by mheap**

### CODE REVIEW

**Comment by arubacao** [comment]
Why should you customize the `baseurl`? Is the sandbox coming back?

**Comment by mheap** [comment]
Afraid not @arubacao. Customising the base URL is useful when debugging, pointing to services such as hookbin

**Comment by mheap** [comment]
It looks like the fix was cherry picked / is no longer in this PR after a rebase. Updated the title to reflect the actual changes (set base URL)

**Comment by lornajane** [comment]
I rebased this against master to check there were no new uses of the constants needing replacement. Also I've separated this so that we don't set both URLs to the same all the time - now we can override either or both, as needed. I'm currently working with the Acount API which uses both endpoints and I might well want to test that they are correctly different, so I thought I'd just add two parameters rather than the one which felt like a bit of a shortcut.

**Pull request merged**
