### PR TITLE
Fix user agent string to conform to the client library spec

### PR DESCRIPTION
**Pull request by mheap**
See https://github.com/Nexmo/client-library-specification/blob/master/SPECIFICATION.md#reporting

Instead of having multiple parts delimited with slashes, each
name/version pair must be it's own entry, separated with a space.

This commit also allows the user to specify an app/name version to help
us identify their traffic if required

### CODE REVIEW

**Comment by leggetter** [comment]
Should we standardize on passing an app name and app version in to the constructor within the spec? Node does a simple userAgent append. See https://github.com/Nexmo/nexmo-node/blob/master/src/Nexmo.js#L56

May be good to aim for consistency. But not a big deal.

**Comment by mheap** [comment]
@leggetter Looking at nexmo-node, the behaviour is the same. If they don't provide any UA we don't do anything. If they do provide a UA we append it to the end.

The only difference is that the node library trusts whatever the user provides (e.g. `a/b/c` which could break our parsing engine) whereas the PHP lib asks for name/version separately and performs validation

**Comment by leggetter** [comment]
I agree the PHP library solution is nicer. My question is: should we standardise on this and make the PHP library the first to adhere to the new standard? Or should we leave this detail to the library developer?

cc @judy2k

**Comment by mheap** [comment]
Standardising sounds like a good idea to me. Especially around disallowed characters + other validation

**Comment by judy2k** [comment]
I missed these comments. I think standardising makes sense, but as a recommendation. I'll make a note to add it to the doc.

**Pull request merged**
