### PR TITLE
Add support for Secret Management

### PR DESCRIPTION
**Pull request by mheap**
This implements the endpoints for the Secret Management API - https://nexmo-developer-staging-pr-579.herokuapp.com/api/account/secret-management

It's the first API that follows RFC7807 for errors (plus our `invalid_parameters` extension for validation errors). To help with this, I've added `ApiErrorHandler::check` which throws formatted exceptions on error.

I've tested `2xx`, `4xx` and `5xx` errors for all of the endpoints, plus an additional test for validation on `createSecret`.

This PR adds two classes, `Secret` and `SecretCollection` for wrapping the API responses. They each have object access and arrayAccess functionality

### CODE REVIEW

**Comment by mheap** [comment]
We can ignore codeclimate for now

**Comment by mheap** [comment]
We need to rename `accountId` to `apiKey` before merging

**Comment by mheap** [comment]
`accountId` renamed to `apiKey`. This is good to merge + tag a release

**Comment by lornajane** [comment]
Did you remove my code examples from the `README` file intentionally? I went to check the code samples one more time and they're no longer present.

**Comment by mheap** [comment]
Ah no, that was a mistake. I must've missed `with-lease` when I pushed.

**Comment by lornajane** [comment]
Ah the dangers of recreational rebasing on shared branches! I can pull it from my reflog, no worries

**Comment by lornajane** [comment]
Do you want a `1.4.1` or a `1.5.0` since we added new API support here?

**Pull request merged**
