### PR TITLE
add `getCost()` to `Number`

### PR DESCRIPTION
**Pull request by arubacao**

### CODE REVIEW

**Comment by mheap** [comment]
👍

I'm away at the moment but I'll cut a new release when I get back

**Comment by arubacao** [comment]
@mheap still planing on merging this?

**Comment by arubacao** [comment]
@mheap still planing on merging this?

**Comment by mheap** [comment]
@arubacao Sorry about the delay merging this - I kept getting your notifications when I was away from home! Releasing as 1.2.1 now

**Pull request merged**
